//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudFormationTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudFormationTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AWSTemplateFormatVersion&quot; : &quot;2010-09-09&quot;,
        ///
        ///  &quot;Description&quot; : &quot;This template enables roles and features of Windows Server. **WARNING** This template creates Amazon EC2 Windows instance and related resources. You will be billed for the AWS resources used if you create a stack from this template.&quot;,
        ///
        ///  &quot;Parameters&quot; : {
        ///    &quot;KeyPairName&quot; : {
        ///      &quot;Description&quot; : &quot;Name of an existing Amazon EC2 key pair for RDP access&quot;,
        ///      &quot;Type&quot; : &quot;String&quot;
        ///    },
        ///    &quot;InstanceType&quot; : {
        ///      &quot;Description&quot; : &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string web_template_after {
            get {
                return ResourceManager.GetString("web_template_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AWSTemplateFormatVersion&quot; : &quot;2010-09-09&quot;,
        ///
        ///  &quot;Description&quot; : &quot;This template enables roles and features of Windows Server. **WARNING** This template creates Amazon EC2 Windows instance and related resources. You will be billed for the AWS resources used if you create a stack from this template.&quot;,
        ///
        ///  &quot;Parameters&quot; : {
        ///    &quot;KeyPairName&quot; : {
        ///      &quot;Description&quot; : &quot;Name of an existing Amazon EC2 key pair for RDP access&quot;,
        ///      &quot;Type&quot; : &quot;String&quot;
        ///    },
        ///    &quot;InstanceType&quot; : {
        ///      &quot;Description&quot; : &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string web_template_before {
            get {
                return ResourceManager.GetString("web_template_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Windows_Roles_And_Features {
            get {
                object obj = ResourceManager.GetObject("Windows_Roles_And_Features", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
